version: '3.7'

services:
  minio:
    image: minio/minio:RELEASE.2020-12-16T05-05-17Z
    container_name: minio_FIMED
    volumes:
      - ./volumes/minio/data:/data
    environment:
      MINIO_ACCESS_KEY: FIMED
      MINIO_SECRET_KEY: FIMEDFIMED
    ports:
      - "9000:9000"
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always